# Site settings
title: 不器用
owner: Jabber Zhou
email: jabber@znn.im
description: "道不可及 器不可信"
baseurl: ""
url: "http://znn.im"
username: mayjabber
disqus_shortname: jabberz
photo: http://www.flickr.com/photos/finalangels
timezone: Asia/Shanghai

# Build settings
encoding: utf-8
highlighter: pygments
markdown: kramdown
permalink: pretty

host: 0.0.0.0
port: 4001
